# Generated by Django 3.2.5 on 2021-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('itemName', models.CharField(max_length=50)),
                ('itemDescription', models.TextField()),
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemWeight', models.IntegerField()),
                ('itemImage', models.ImageField(upload_to='')),
                ('inventoryCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderName', models.CharField(max_length=50)),
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('orderRecipientFirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('orderRecipientLastName', models.CharField(blank=True, max_length=50, null=True)),
                ('orderRecipientBuildingNumber', models.IntegerField(blank=True, null=True)),
                ('orderRecipientStreetName', models.CharField(blank=True, max_length=50, null=True)),
                ('orderRecipientCityName', models.CharField(blank=True, max_length=50, null=True)),
                ('orderRecipientStateName', models.CharField(blank=True, max_length=20, null=True)),
                ('orderRecipientZipCode', models.IntegerField(blank=True, null=True)),
                ('orderRecipientPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('orderRecipientEmail', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckModel', models.CharField(max_length=50)),
                ('truckNumber', models.IntegerField()),
                ('maxCarryingCapacity', models.IntegerField()),
            ],
        ),
    ]
